version: '0.0.2.{build}'

branches:
  only:
    - master

skip_tags: true

skip_commits:
  files:
    - '**\README.md'
    - LICENSE.txt

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: 'Hateblo\Hateblo.csproj;Hateblo.Tests\Hateblo.Tests.csproj'
  assembly_version: '{version}'
  file_version: '{version}'

configuration: Release

build:
  project: Hateblo.sln

before_build:
  - git submodule init
  - git submodule update
  - nuget restore

after_build:
  - dotnet pack Hateblo\Hateblo.csproj -c Release --no-build /p:NuspecFile=Hateblo.nuspec
  - ps: Get-ChildItem Hateblo\bin\Release\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

artifacts:
  - path: Hateblo\bin\$(configuration)
    name: Hateblo

deploy:
  provider: NuGet
  api_key:
    secure: 9oF7osqItmiaY4ei1hrI0MeSdjc1NR3zyfvQIZeYMlaevgUVSYiAITdSLw2KtM0j
  skip_symbols: true
